import { BlogPost } from "../types/blog-types";

export const BLOG_POSTS: BlogPost[] = [
  {
    id: 1,
    title: "Sed ut perspiciatis unde omnis iste natus",
    excerpt: "There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in som...",
    image: "/images/blog1.png",
    date: "March 21, 2018",
    author: "Admin",
    category: "Fashion",
    slug: "sed-ut-perspiciatis",
  },
  {
    id: 2,
    title: "Voluptatem accusantium dolor emque totam",
    excerpt: "Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin from...",
    image: "/images/blog2.png",
    date: "March 21, 2018",
    author: "Admin",
    category: "Lifestyle",
    slug: "voluptatem-accusantium",
  },
  {
    id: 3,
    title: "Eaque ipsa quae ab illo inventore veritatis et",
    excerpt: "There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in som...",
    image: "/images/blog3.png",
    date: "March 21, 2018",
    author: "Admin",
    category: "Design",
    slug: "eaque-ipsa-quae",
  },
  {
    id: 4,
    title: "Magni dolores eos qui ratione voluptatem sequi",
    excerpt: "Contrary to popular belief, Lorem Ipsum is not simply used random text. It has roots in a piece of classical Latin from...",
    image: "/images/blog4.png",
    date: "March 21, 2018",
    author: "Admin",
    category: "Fashion",
    slug: "magni-dolores",
  },
  {
    id: 5,
    title: "Neque porro quisquam est qui dolorem ipsum",
    excerpt: "There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in som...",
    image: "/images/blog5.png",
    date: "March 21, 2018",
    author: "Admin",
    category: "Lifestyle",
    slug: "neque-porro",
  },
  {
    id: 6,
    title: "Quia dolor sit amet consectetur adipisci velit",
    excerpt: "Contrary to popular belief, Lorem Ipsum is not simply used random text. It has roots in a piece of classical Latin from...",
    image: "/images/blog6.png",
    date: "March 21, 2018",
    author: "Admin",
    category: "Travel",
    slug: "quia-dolor",
  },
];
