import { BlogPost } from "../types/blog-types";

export const BLOG_POSTS: BlogPost[] = [
  {
    id: 1,
    title: "Sức hút của phong cách thời trang tối giản trong năm 2024",
    excerpt: "Phong cách tối giản (Minimalism) không bao giờ lỗi mốt. Hãy cùng khám phá cách phối đồ tinh tế nhưng vẫn đầy quyền lực...",
    image: "/images/blog1.png",
    date: "21 Tháng 3, 2024",
    author: "Quản trị viên",
    category: "Thời trang",
    slug: "phong-cach-toi-gian-2024",
  },
  {
    id: 2,
    title: "5 bí quyết giữ cho quần áo luôn bền đẹp như mới",
    excerpt: "Việc chăm sóc quần áo đúng cách không chỉ giúp bạn tiết kiệm chi phí mà còn bảo vệ môi trường. Dưới đây là những mẹo nhỏ...",
    image: "/images/blog2.png",
    date: "20 Tháng 3, 2024",
    author: "Quản trị viên",
    category: "Lối sống",
    slug: "bi-quyet-giu-quan-ao-ben-dep",
  },
  {
    id: 3,
    title: "Xu hướng màu sắc chủ đạo cho mùa hè năm nay",
    excerpt: "Mùa hè này, những gam màu rực rỡ và tươi mới đang chiếm lĩnh sàn diễn thời trang. Hãy cùng điểm qua những tông màu...",
    image: "/images/blog3.png",
    date: "18 Tháng 3, 2024",
    author: "Quản trị viên",
    category: "Thiết kế",
    slug: "xu-huong-mau-sac-mua-he",
  },
  {
    id: 4,
    title: "Cách phối đồ với denim sao cho thật phong cách",
    excerpt: "Denim là chất liệu không thể thiếu trong tủ đồ của bất kỳ ai. Tuy nhiên, phối đồ với denim thế nào để không bị nhàm chán...",
    image: "/images/blog4.png",
    date: "15 Tháng 3, 2024",
    author: "Quản trị viên",
    category: "Thời trang",
    slug: "cach-phoi-do-denim",
  },
  {
    id: 5,
    title: "Tầm quan trọng của phụ kiện trong việc định hình phong cách",
    excerpt: "Đôi khi một bộ trang phục đơn giản sẽ trở nên nổi bật hơn bao giờ hết chỉ nhờ vào một vài món phụ kiện được chọn lựa...",
    image: "/images/blog5.png",
    date: "10 Tháng 3, 2024",
    author: "Quản trị viên",
    category: "Lối sống",
    slug: "tam-quan-trong-phu-kien",
  },
  {
    id: 6,
    title: "Hành trình tìm kiếm nguồn cảm hứng thiết kế mới",
    excerpt: "Nguồn cảm hứng có thể đến từ bất cứ đâu: một chuyến đi, một bộ phim hay đơn giản là một buổi chiều dạo phố...",
    image: "/images/blog6.png",
    date: "05 Tháng 3, 2024",
    author: "Quản trị viên",
    category: "Du lịch",
    slug: "nguon-cam-hung-thiet-ke",
  },
];
